export const materials = [
  { code: 'MASA', name: 'Acetilsalicilna kiselina', measurementUnit: 'g' },
  { code: 'MLAK', name: 'Laktoza', measurementUnit: 'g' },
  { code: 'MMCC', name: 'Mikrokristalna celuloza', measurementUnit: 'g' },
  { code: 'MMAG', name: 'Magnezijum-stearat', measurementUnit: 'g' },
  { code: 'MPAR', name: 'Paracetamol', measurementUnit: 'g' },
  { code: 'MCEL', name: 'Celuloza', measurementUnit: 'g' },
  { code: 'MNSG', name: 'Natrijum skrob glikolat', measurementUnit: 'g' },
  { code: 'MAMX', name: 'Amoksicilin', measurementUnit: 'g' },
  { code: 'MNCS', name: 'Natrijum karboksimetil skrob', measurementUnit: 'g' },
  { code: 'MKSD', name: 'Koloidni silicijum dioksid', measurementUnit: 'g' },
  { code: 'MIBO', name: 'Iboprofen', measurementUnit: 'g' },
  { code: 'MLOR', name: 'Loratadin', measurementUnit: 'g' },
  { code: 'MOME', name: 'Omeprazol', measurementUnit: 'g' },
  { code: 'MPOV', name: 'Povidon', measurementUnit: 'g' },
  { code: 'MNLS', name: 'Natrijum laurilsulfat', measurementUnit: 'g' },
  { code: 'MSIM', name: 'Simvastatin', measurementUnit: 'g' },
  { code: 'MMET', name: 'Metformin', measurementUnit: 'g' },
  { code: 'MATO', name: 'Atorvastatin', measurementUnit: 'g' },
  { code: 'MLOS', name: 'Losartan', measurementUnit: 'g' },
];